version: 2.1
executors:
  node-lts:
    docker:
      - image: circleci/node:16

jobs:
  setup:
    executor: node-lts
    steps:
      - run: sudo apt-get install jq
  install:
    executor: node-lts
    steps:
      - checkout
      - run: npm install
      - persist_to_workspace:
          root: ./
          paths:
            - ./*
  build:
    executor: node-lts
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: npm run package
      - persist_to_workspace:
          root: ./
          paths:
            - ./*
  version-and-publish:
    executor: node-lts
    steps:
      - attach_workspace:
          at: .
      - run: npx semantic-release

workflows:
  build-test-deploy:
    jobs:
      - setup
      - install:
          requires:
            - setup
      - build:
          requires:
            - install
      - version-and-publish:
          context:
            - github-versioning
            - npm-publishing
          requires:
            - build
          filters:
            branches:
              only:
                - main
